services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab.local
    restart: always
    ports:
      - "8080:80"
      - "8929:22"
    environment:
      GITLAB_ROOT_EMAIL: root@local
      GITLAB_ROOT_PASSWORD: CakeEggMilk11!@
      EXTERNAL_URL: http://gitlab.local
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data: