expose:
  type: nodePort
  tls:
    enabled: false
  nodePort:
    name: http
    ports:
      http:
        nodePort: 30003
        port: 80

externalURL: http://localhost:30003

persistence:
  enabled: false

internalTLS:
  enabled: false