apiVersion: v1
kind: Service
metadata:
  name: nodeport-test
  namespace: default
spec:
  type: NodePort
  selector:
    app: dummy
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30800
